// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIK6r9paGyS_hZ7R6Cf9WxXC5ozGtb4oo',
    appId: '1:1014184733930:web:0438a0a8c562952a8afb93',
    messagingSenderId: '1014184733930',
    projectId: 'smart-farm-d21ae',
    authDomain: 'smart-farm-d21ae.firebaseapp.com',
    databaseURL: 'https://smart-farm-d21ae-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-d21ae.firebasestorage.app',
    measurementId: 'G-RX36589XV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcJ-ksjk2da_DTeuIapfdwGfhn5Aff5fE',
    appId: '1:1014184733930:android:aeaddb3082690dc88afb93',
    messagingSenderId: '1014184733930',
    projectId: 'smart-farm-d21ae',
    databaseURL: 'https://smart-farm-d21ae-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-d21ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwAHbIw2aLV_kW5PNPAdJY82Kx0RsisuU',
    appId: '1:1014184733930:ios:4676cdd1972a780c8afb93',
    messagingSenderId: '1014184733930',
    projectId: 'smart-farm-d21ae',
    databaseURL: 'https://smart-farm-d21ae-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-d21ae.firebasestorage.app',
    iosBundleId: 'com.example.happyfarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwAHbIw2aLV_kW5PNPAdJY82Kx0RsisuU',
    appId: '1:1014184733930:ios:4676cdd1972a780c8afb93',
    messagingSenderId: '1014184733930',
    projectId: 'smart-farm-d21ae',
    databaseURL: 'https://smart-farm-d21ae-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-d21ae.firebasestorage.app',
    iosBundleId: 'com.example.happyfarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIK6r9paGyS_hZ7R6Cf9WxXC5ozGtb4oo',
    appId: '1:1014184733930:web:3a2221fb3e42fcf68afb93',
    messagingSenderId: '1014184733930',
    projectId: 'smart-farm-d21ae',
    authDomain: 'smart-farm-d21ae.firebaseapp.com',
    databaseURL: 'https://smart-farm-d21ae-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-d21ae.firebasestorage.app',
    measurementId: 'G-4PPHYH9W9T',
  );
}
